(load "1.28-expmod.scm")
(load "1.28-non-zero-random.scm")

(define (Miller-Rabin-test n)
  (define (iter n times)
    (cond ((= times 0) #t)
          ((= (expmod (non-zero-random n) (- n 1) n)
              1)
           (iter n (- times 1)))
          (else #f)))
  (iter n (ceiling (/ n 2))))